### ISSUE TITLE
where are you referring?

### ISSUE THREAD

**Issue by jurgens1206** [smthemex/ComfyUI_FoleyCrafter#6]
Hello.
I have successfully confirmed that this framework works, but I have one question. I don't know where "video_files" shown in the screenshot refers to on my computer. I would like to change it to any folder, so please let me know.
![new0906](https://github.com/user-attachments/assets/65346729-318e-4df2-b9aa-6a6691a42b5e)

**Comment by smthemex** [comment]
The default directory is comfyUI/input

**Comment by jurgens1206** [comment]
When I tried to copy the video file, it appeared. thank you very much.
